### ISSUE TITLE
Twocheckout_Sale::stop Recurring item problem

### ISSUE THREAD

**Issue by ahmetemir** [2Checkout/2checkout-php#20]
In Twocheckoutsale.php
```
$lineitemData = Twocheckout_Util::getRecurringLineitems($result);
if (isset($lineitemData[0])) {
...
}
```
If recurring item is not the first line item,it throws "**No recurring lineitems to stop**".And in my situation array returned from **getRecurringLineitems** function has index starting from **1**.Please replace this line with:
```
if (count($lineitemData)>0) {

}
```

**Comment by craigchristenson** [comment]
Thanks for reporting this issue. The issue has been fixed so that we properly push the lineitems to the array, resulting in the expected index.

**Comment by umutm** [comment]
This issue still existed for me.

I believe that the getRecurringLineitems function in Twocheckoututil.php was not getting the latest invoice in a sale properly and changing:

`$invoice = max($invoiceData);`
to 
`$invoice = end($invoiceData);`
in Twocheckoututil.php worked for me.
